### ISSUE TITLE
你好，请问可以借你的代码用用么。

### ISSUE THREAD

**Issue by pandaTerminator** [wendell-git/FirstMusic#1]
本人前端，现在学校要写个安卓程序，想借你的用用，可以发给我一份源代码吗？谢谢。

**Comment by wendell-git** [comment]
这份代码我也是在别人基础上做的修改，如果需要直接在github 上就可以下载。

发自 网易邮箱大师
在2015年10月26日 14:17，pandasjw 写道:

本人前端，现在学校要写个安卓程序，想借你的用用，可以发给我一份源代码吗？谢谢。

**Comment by pandaTerminator** [comment]
就是下载哪部分可以直接用？毕竟不懂安卓，求指教，不会让我全部拷了吧。。。

**Comment by wendell-git** [comment]
是的，全部拷贝就可以，那整个就是个eclipse 工程，拷贝到本地用eclipse 导入就行了。

发自 网易邮箱大师
在2015年10月27日 16:55，pandasjw 写道:

就是下载哪部分可以直接用？毕竟不懂安卓，求指教，不会让我全部拷了吧。。。

**Comment by pandaTerminator** [comment]
非常感谢。。。。

**Comment by pandaTerminator** [comment]
请问你的代码里面有没有歌曲呀？在哪个目录下呀？
